server:
  port: 18082
spring:
  application:
    name: user-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true #请求压缩
      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
      min-request-size: 2048
    response:
      enabled: true #响应压缩

  logging:
    level:
      com.edu: debug

